Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/test/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/share/miniconda3/envs/test/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda3/envs/test/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/share/miniconda3/envs/test/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/share/miniconda3/envs/test/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/share/miniconda3/envs/test/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda3/envs/test/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/share/miniconda3/envs/test/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
scale = 1e-4
wrk = op.Workspace()
wrk.settings['loglevel'] = 50
wrk.clear()
np.random.seed(1)
proj = op.materials.VoronoiFibers(points=100,
                                  fiber_rad=5e-6,
                                  resolution=1e-6,
                                  shape=[scale, scale, scale],
                                  name='test')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn [2], line 6[0m
[1;32m      4[0m wrk[38;5;241m.[39mclear()
[1;32m      5[0m np[38;5;241m.[39mrandom[38;5;241m.[39mseed([38;5;241m1[39m)
[0;32m----> 6[0m proj [38;5;241m=[39m [43mop[49m[38;5;241;43m.[39;49m[43mmaterials[49m[38;5;241m.[39mVoronoiFibers(points[38;5;241m=[39m[38;5;241m100[39m,
[1;32m      7[0m                                   fiber_rad[38;5;241m=[39m[38;5;241m5e-6[39m,
[1;32m      8[0m                                   resolution[38;5;241m=[39m[38;5;241m1e-6[39m,
[1;32m      9[0m                                   shape[38;5;241m=[39m[scale, scale, scale],
[1;32m     10[0m                                   name[38;5;241m=[39m[38;5;124m'[39m[38;5;124mtest[39m[38;5;124m'[39m)

[0;31mAttributeError[0m: module 'openpnm' has no attribute 'materials'
AttributeError: module 'openpnm' has no attribute 'materials'

