Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/test/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/share/miniconda3/envs/test/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda3/envs/test/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/share/miniconda3/envs/test/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/share/miniconda3/envs/test/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/share/miniconda3/envs/test/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda3/envs/test/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/share/miniconda3/envs/test/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from pathlib import Path
path = Path('../_fixtures/ICL-Sandstone(Berea)/')
project = op.io.Statoil.import_data(path=path, prefix='Berea')
pn = project.network
pn.name = 'berea'
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn [2], line 3[0m
[1;32m      1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpathlib[39;00m [38;5;28;01mimport[39;00m Path
[1;32m      2[0m path [38;5;241m=[39m Path([38;5;124m'[39m[38;5;124m../_fixtures/ICL-Sandstone(Berea)/[39m[38;5;124m'[39m)
[0;32m----> 3[0m project [38;5;241m=[39m [43mop[49m[38;5;241;43m.[39;49m[43mio[49m[38;5;241;43m.[39;49m[43mStatoil[49m[38;5;241m.[39mimport_data(path[38;5;241m=[39mpath, prefix[38;5;241m=[39m[38;5;124m'[39m[38;5;124mBerea[39m[38;5;124m'[39m)
[1;32m      4[0m pn [38;5;241m=[39m project[38;5;241m.[39mnetwork
[1;32m      5[0m pn[38;5;241m.[39mname [38;5;241m=[39m [38;5;124m'[39m[38;5;124mberea[39m[38;5;124m'[39m

[0;31mAttributeError[0m: module 'openpnm.io' has no attribute 'Statoil'
AttributeError: module 'openpnm.io' has no attribute 'Statoil'

